name: CI et CD todo app
on:
  push:
    branches: [ main ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci --legacy-peer-deps
      - run: npm test
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.ACCESSTOKEN }}
      - name: 🚀 Build app
        run: eas build --platform android --non-interactive --no-wait
